---
- name: "Check if zsh is installed"
  ansible.builtin.command: which zsh
  register: zsh_check
  failed_when: false
  changed_when: false

- name: "Install zsh if not present"
  become: true
  become_method: sudo
  ansible.builtin.package:
    name: zsh
    state: present
  when: zsh_check.rc != 0

- name: "Copy ZshRC"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
  become: false

- name: "Removing Kali developers msg"
  ansible.builtin.shell:
    cmd: touch {{ ansible_env.HOME }}/.hushlogin
  become: false

- name: "Set zsh as default shell"
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  when: zsh_check.rc == 0
