---
- name: "Install Rust via apt"
  ansible.builtin.apt:
    update_cache: true
    name:
      - rustc
      - cargo
      - build-essential
    state: present
  become: true

- import_tasks: rust-tools.yml
