---
- name: Update and upgrade apt packages
  become: true
  become_method: sudo
  ansible.builtin.apt:
    upgrade: no
    update_cache: yes
    cache_valid_time: 86400 #One day
  
- name: "Installing Packages"
  ansible.builtin.package:
    name:
      - jq
      - curl
      - pipx
      - golang
      - zsh
      - docker.io
      - docker-compose
      - openjdk-17-jre
      - unzip
      - libpcap-dev
    state: latest
  become: true
  become_method: sudo