---
- name: "Install SQLi tools"
  ansible.builtin.shell: "{{ item.command }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  loop:
    - { command: "pip install sqlmap" }
    - { command: "pip install ghauri" }

- name: "Install Cert Monitoring tools"
  ansible.builtin.shell: "{{ item.command }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  loop:
    - { command: "pip install certstream" }
    - { command: "pip install certstream-go" }

- name: "Install API Discovery tools"
  ansible.builtin.shell: "{{ item.command }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  loop:
    - { command: "pip install arjun" }
    - { command: "pip install x8" }
    - { command: "pip install paramspider" }

- name: "Install Cloud tools"
  ansible.builtin.shell: "{{ item.command }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  loop:
    - { command: "pip install awscli" }
    - { command: "pip install cloudenum" }
    - { command: "pip install s3scanner" }

- name: "Install OSINT tools"
  ansible.builtin.shell: "{{ item.command }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  loop:
    - { command: "pip install shodan" }
    - { command: "pip install censys" }
    - { command: "pip install metabigor" }

- name: "Install Scope Management tools"
  ansible.builtin.shell: "{{ item.command }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  loop:
    - { command: "pip install bbrf" }