---
- name: "BBForge - Bug Bounty Environment Setup"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/install-bb-workflows"
    - role: "roles/install-rust"
    - role: "roles/install-burpsuite"
    - role: "roles/config-tmux"
    - role: "roles/config-terminal"
    - role: "roles/config-browser"
    - role: "roles/config-obsidian"
    - role: "roles/install-vscode"
    - role: "roles/config-keyboard"
