- name: "Check if BurpSuiteCA.der exists"
  ansible.builtin.stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert
  
- name: "Copying Burp Script"
  ansible.builtin.copy:
    src: files/getburpcert.sh
    dest: /tmp/getburpcert.sh
    mode: '0744'
  when: not burp_cert.stat.exists
  become: false

- name: "Executing bash script to Download CA Certificate"
  ansible.builtin.shell:
    cmd: /tmp/getburpcert.sh
  when: not burp_cert.stat.exists
  become: false

- name: "Copying CA Certificate to /usr/local/share/ca-certificates"
  ansible.builtin.copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: not burp_cert.stat.exists

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    mode: '0644'
  become: true
  become_method: sudo
  loop: "{{ burpsuite_extras_jars | dict2items }}"
  
- name: "Ensure .BurpSuite directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.BurpSuite"
    state: directory
    mode: '0755'
  become: false
  
- name: Copy BurpSuite Community Config
  ansible.builtin.template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "{{ ansible_env.HOME }}/.BurpSuite/UserConfigCommunity.json"
  become: false

